version: "3.4"

x-logging:
  &default-logging
  options:
    max-size: "100M"
    max-file: "5"

services:
  postgres:
    image: postgres:13
    restart: always
    logging: *default-logging
    env_file:
      - envs/.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:22.6-alpine
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8123' ]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: user
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: password
#    volumes:
#      - ./click_rabbit_config/cluster_config.xml:/etc/clickhouse-server/config.d/local.xml
#      - ./click_rabbit_config/macros01.xml:/etc/clickhouse-server/config.d/macros.xml
#      - ./click_rabbit_config/rabbitmq.xml:/etc/clickhouse-server/config.d/rabbitmq.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    ports:
#      - 9090:9090
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
#    depends_on:
#      -

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    env_file:
      - envs/.env
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  postgres-data:
  rabbitmq-data: